### ISSUE TITLE
如何在tumblr中设置分享自己的likes

### ISSUE THREAD

**Issue by elftech** [cyang812/get_tumblr_likes#11]
，是在privacy dashboard里面吗？可是现在完全登不了这个页面。一直提示要证明自己不是机器人，但验证码刷不出来。用的是vps shadowsock上网。

**Comment by SHY1226** [comment]
https://www.tumblr.com/settings/blog/你的用户名

**Comment by elftech** [comment]
__

> https://www.tumblr.com/settings/blog/你的用户名

恩 谢谢
