### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by SHY1226** [cyang812/get_tumblr_likes#12]
以下是错误信息
> <Response [200]>
like_item =  924
<Response [200]>
res_item_len =  0
Traceback (most recent call last):
  File "run.py", line 13, in <module>
    get_json_v3.main()
  File "/root/tumblr-download/get_tumblr_likes/get_json_v3.py", line 62, in main
    liked_timestamp = data['response']['liked_posts'][res_item_len-1]['liked_timestamp']
IndexError: list index out of range

查了一下应该是返回的数据中有空格导致读取时出错，求修复

**Comment by elftech** [comment]
也遇到了相同的问题。同求help

**Comment by cyang812** [comment]
建议分步骤运行下。
get_json_v2.py 或者 get_json_v3.py，然后 json_parse.py, 之后在用 download_thread.py 下载。

**Comment by elftech** [comment]
原因是liked_posts为空。但我的账号的确设置了sharing likes

**Comment by elftech** [comment]
返回是这个，like列表为空：
{'meta': {'status': 200, 'msg': 'OK'}, 'response': {'liked_posts': [], 'liked_count': 249}}

**Comment by SHY1226** [comment]
今天再试了一次，不知道为什么又可以正常获取地址了，但是获取到的文件只有664个，而我用别的工具获取到的文件接近2600个，尝试的多次结果都是一样的，只不过我已经备份完了，也懒得折腾了
