### ISSUE TITLE
两种方案都失败了

### ISSUE THREAD

**Issue by bluefo** [cyang812/get_tumblr_likes#6]
Hi，感谢您能在当下提供这么好的工具。

我尝试使用 get_json_v3，结果报错；

>  #1 get_json main()
> Please input blog_id:XXXXX
> <Response [200]>
> like_item =  275
> <Response [200]>
> res_item_len =  0
> Traceback (most recent call last):
>   File "run.py", line 14, in <module>
>     get_json_v3.main()
>   File "/Users/Me/Downloads/get_tumblr_likes-master/get_json_v3.py", line 62, in main
>     liked_timestamp = data['response']['liked_posts'][res_item_len-1]['liked_timestamp']
> IndexError: list index out of range

如果使用 get_json_v2，则这样婶儿的：

> #1 get_json main()
> tumblr.cfg
> <Response [200]>
> like_item =  275
> <Response [200]>
> res_item_len =  1
> liked_timestamp = 1543907623
> <Response [200]>
> res_item_len =  11
> liked_timestamp = 1538609700
> <Response [200]>
> res_item_len =  11
> liked_timestamp = 1527015559
> <Response [200]>
> res_item_len =  11
> liked_timestamp = 1521760899
> <Response [200]>
> res_item_len =  11
> liked_timestamp = 1517356355
> <Response [200]>
> res_item_len =  11
> liked_timestamp = 1516033795
> <Response [200]>
> res_item_len =  11
> liked_timestamp = 1513725378
> <Response [200]>
> res_item_len =  11
> liked_timestamp = 1511711973
> <Response [200]>
> res_item_len =  11
> liked_timestamp = 1509577245
> <Response [200]>
> res_item_len =  11
> liked_timestamp = 1506825792
> <Response [200]>
> res_item_len =  11
> liked_timestamp = 1504627361
> <Response [200]>
> res_item_len =  11
> liked_timestamp = 1502205643
> <Response [200]>
> res_item_len =  11
> liked_timestamp = 1501599278
> <Response [200]>
> res_item_len =  11
> liked_timestamp = 1481893975
> <Response [200]>
> res_item_len =  10
> liked_timestamp = 1462874347
> <Response [200]>
> res_item_len =  0
> #2 json_parse main()
> list_len =  15
> item_len =  1
> item_len =  11
> item_len =  11
> item_len =  11
> item_len =  11
> item_len =  11
> item_len =  11
> item_len =  11
> item_len =  11
> item_len =  11
> item_len =  11
> item_len =  11
> item_len =  11
> item_len =  11
> item_len =  10
> item total =  154
> #3 download_process main()
> downloading...............
> list_len =  473

然后就卡着了完全不动……看了下 url_list.txt 已经有 url 了，url 通过浏览器也能打开。

希望能够得到您的解答，不尽感激～

**Comment by cyang812** [comment]
第一种的 get_json_v3 返回的likes.json有没有数据，有的话 json_parse.py, 再download_process.py。

第二种看起来没问题，后面在下载只是因为多进程，没有打印消息出来，其实应该已经在下载了，你可以过段时间在本地文件看到。或者你换另外两种下载方法。

**Comment by dudukee** [comment]
get_json_v3返回格式变了 解析会出现异常

```
{"meta":{"status":200,"msg":"OK"},"response":{"liked_posts":[],"liked_count":143}}
```

**Comment by bluefo** [comment]
> 第一种的 get_json_v3 返回的likes.json有没有数据，有的话 json_parse.py, 再download_process.py。
> 
> 第二种看起来没问题，后面在下载只是因为多进程，没有打印消息出来，其实应该已经在下载了，你可以过段时间在本地文件看到。或者你换另外两种下载方法。

非常感谢答复！
通过v2可以正常使用了，刚才发现实际上是梯子的问题，真抱歉。
多线程下载速度很快，不过下载了一部分只有243字节的视频。像这样的：
https://vt.tumblr.com/tumblr_o6r06dqq2R1u7poit.mp4

我在这里看到类似的问题：
https://github.com/dixudx/tumblr-crawler/issues/17
所以，应该是资源已经被服务器移除了？

**Comment by elftech** [comment]
> > 第一种的 get_json_v3 返回的likes.json有没有数据，有的话 json_parse.py, 再download_process.py。
> > 第二种看起来没问题，后面在下载只是因为多进程，没有打印消息出来，其实应该已经在下载了，你可以过段时间在本地文件看到。或者你换另外两种下载方法。
> 
> 非常感谢答复！
> 通过v2可以正常使用了，刚才发现实际上是梯子的问题，真抱歉。
> 多线程下载速度很快，不过下载了一部分只有243字节的视频。像这样的：
> https://vt.tumblr.com/tumblr_o6r06dqq2R1u7poit.mp4
> 
> 我在这里看到类似的问题：
> [dixudx/tumblr-crawler#17](https://github.com/dixudx/tumblr-crawler/issues/17)
> 所以，应该是资源已经被服务器移除了？

v2中的consumerkey大家都是如何申请的？

**Comment by yqn3216308** [comment]
纯小白一路找到这里  不怎么会用  api也获取了

**Comment by yqn3216308** [comment]
纯小白一路找到这里  不怎么会用  api也获取了
