### ISSUE TITLE
请问如何获取blog_id

### ISSUE THREAD

**Issue by SHY1226** [cyang812/get_tumblr_likes#9]
似乎不是用户名，不想申请api_key，请问如何获取自己的blog_id

**Comment by charletson** [comment]
左上角就是ID，ID.tumblr.com

**Comment by SHY1226** [comment]
之前试的时候都不行，返回429，现在又好了，但是报了个错

> <Response [200]>
like_item =  924
<Response [200]>
res_item_len =  0
Traceback (most recent call last):
  File "get_json_v3.py", line 104, in <module>
    main()
  File "get_json_v3.py", line 62, in main
    liked_timestamp = data['response']['liked_posts'][res_item_len-1]['liked_timestamp']
IndexError: list index out of range
好像是数量太多了？
